name: canary remove

on:
  issue_comment:
    types: [ created ]

jobs:
  canary-publish:
    name: canary-remove
    runs-on: ubuntu-latest
    if:
      (github.event.comment.author_association == 'MEMBER' || github.event.comment.author_association == 'OWNER' || github.event.comment.author_association == 'CONTRIBUTOR') &&
      startsWith(github.event.comment.body, '/canary-remove')
    steps:
      - name: get pr information
        uses: actions/github-script@v4
        id: pr
        with:
          script: |
            const request = {
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.issue.number
            }

            core.info(`Getting PR #${request.pull_number} from ${request.owner}/${request.repo}`)
            try {
              const result = await github.pulls.get(request)
              core.info(`Got PR: ${JSON.stringify(result.data)}`)
              return result.data
            } catch (err) {
              core.setFailed(`Request failed with error ${err}`)
            }

      - name: checkout pr version
        uses: actions/checkout@v2
        with:
          ref: ${{ fromJSON(steps.pr.outputs.result).head.ref }}
          repository: ${{ fromJSON(steps.pr.outputs.result).head.repo.full_name }}
          fetch-depth: 0

      - name: setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 14.x

      - name: set npm autority
        run: |
          yarn logout
          echo "@apollo-elements:registry=http://registry.npmjs.org/" > .npmrc
          echo "registry=http://registry.npmjs.org/" >> .npmrc
          echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> .npmrc
          npm whoami
        env:
          NPM_TOKEN: ${{ secrets.npm_token }}

      - name: get lerna packages list
        id: packages
        run: echo "::set-output name=list::$(lerna list --json | awk '{print}' ORS='')"

      - name: echo packages list
        uses: actions/github-script@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            let { LIST } = process.env;

            core.info(`list: ${LIST}`);
            LIST = JSON.parse(LIST);

            LIST.forEach((item) => {
              core.info(`item: ${item.name}`);
            });

        env:
          LIST: ${{ steps.packages.outputs.list }}

      - name: PR comment
        if: always()
        uses: actions/github-script@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { STATUS, NUMBER } = process.env;

            let message = '';
            switch (STATUS) {
              case 'success':
                message = `🎉 canary remove complete! Removed tag is \`alpha-${NUMBER}\``;
                break;

              case 'failure':
                message = '❗ canary remove failed. Check error in github action page.';
                break;
            }

            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: message
            })

        env:
          STATUS: ${{ job.status }}
          NUMBER: ${{ fromJSON(steps.pr.outputs.result).number }}
