name: canary publish

on:
  issue_comment:
    types: [ created ]

jobs:
  start-comment:
    name: start comment
    runs-on: ubuntu-latest
    if:
      (github.event.comment.author_association == 'MEMBER' || github.event.comment.author_association == 'OWNER' || github.event.comment.author_association == 'CONTRIBUTOR') &&
      startsWith(github.event.comment.body, '/canary-publish')
    steps:
      - name: Comment to command
        uses: hasura/comment-progress@v2.1.0
        with:
          id: canary-publish-comment-${{ github.run_id }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.repository }}
          number: ${{ github.event.issue.number }}
          message: |
            > /canary-publish

            Trying to publish canary version...
            If you want to see detailed execution status, please [click here](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}).

  get-data:
    name: get data
    runs-on: ubuntu-latest
    if:
      (github.event.comment.author_association == 'MEMBER' || github.event.comment.author_association == 'OWNER' || github.event.comment.author_association == 'CONTRIBUTOR') &&
      startsWith(github.event.comment.body, '/canary-publish')
    steps:
      - name: checkout pull request version
        uses: actions/checkout@v2
        with:
          ref: ${{ github.sha }}

      - name: get pr information
        uses: actions/github-script@v4
        id: pr
        with:
          script: |
            const { getPrData } = require('./.github/scripts');
            return await getPrData({ github, context, core });

      - name: make data file
        env:
          PR: ${{ steps.pr.outputs.result }}
        run: |
          mkdir ./data
          echo $PR > data/pr.json

      - name: upload data file
        uses: actions/upload-artifact@v2
        with:
          name: data
          path: data

  canary-publish:
    needs: [get-data]
    name: canary publish
    runs-on: ubuntu-latest
    if:
      (github.event.comment.author_association == 'MEMBER' || github.event.comment.author_association == 'OWNER' || github.event.comment.author_association == 'CONTRIBUTOR') &&
      startsWith(github.event.comment.body, '/canary-publish')
    steps:
      - name: download data file
        uses: actions/download-artifact@v2
        with:
          name: data

      - name: set data value
        id: data
        run: |
          echo "::set-output name=pr::$(cat pr.json)"

      - name: checkout pr version
        uses: actions/checkout@v2
        with:
          ref: ${{ fromJSON(steps.data.outputs.pr).head.ref }}
          repository: ${{ fromJSON(steps.data.outputs.pr).head.repo.full_name }}
          fetch-depth: 0

      - name: setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 14.x

      - name: set npm autority
        run: |
          yarn logout
          echo "@apollo-elements:registry=http://registry.npmjs.org/" > .npmrc
          echo "registry=http://registry.npmjs.org/" >> .npmrc
          echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> .npmrc
          npm whoami
        env:
          NPM_TOKEN: ${{ secrets.npm_token }}

      - name: install dependencies
        run: yarn install

      - name: build all packages
        run: lerna run build

      - name: publish package
        id: published
        run: |
          RESULT=$(lerna publish --canary --conventional-prerelease --preid alpha-${{ env.NUMBER }} --dist-tag alpha-${{ env.NUMBER }} --no-push --no-git-tag-version --yes)
          echo "::set-output name=result::$(echo $RESULT | awk '{print}' ORS='\\n')"
        env:
          NUMBER: ${{ fromJSON(steps.data.outputs.pr).number }}

      - name: parsing published packages
        id: published-packages
        uses: actions/github-script@v4
        with:
          script: |
            const { PUBLISHED } = process.env;

            core.info(`published test : \n${PUBLISHED}`);

            const regexp = /(?<=Successfully published:\\n)( - ([\w@/.\-+]+)(?:\\n)?)*/gm;
            const listText = PUBLISHED.match(regexp)[0];

            core.info(`list text : \n${listText}`);

            const packageListRegexpt = /(?<= - )([\w@/.\-+]+)/g
            const packageList = listText.match(packageListRegexpt);

            return packageList;

        env:
          PUBLISHED: ${{ steps.published.outputs.result }}

      - name: echo published-packges
        run: echo ${{ steps.published-packages.outputs.result }}


      - name: make comment
        if: always()
        id: comment
        uses: actions/github-script@v4
        with:
          script: |
            const { STATUS, TAG, ACTION_URL } = process.env;

            /*
            let { PACKAGES } = process.env;
            PACKAGES = JSON.parse(PACKAGES);
            */

            let message = "> /canary-publish\r\n\r\n";
            switch (STATUS) {
              case 'success':
                message += `🎉 canary publish complete!\r\n`;
                message += `You can install canary version via \`yarn add package@${TAG}\`\r\n\r\n`
                message += '**Package list**\r\n'
                /*PACKAGES.forEach(({ name }) => {
                  message += `- ${name}\r\n`
                });*/

                break;

              case 'failure':
                message += `❗ canary publish failed.\r\nCheck error in github [action page](${ACTION_URL}).\r\n`;
                break;
            }

            return { message };
        env:
          STATUS: ${{ job.status }}
          TAG: alpha-${{ fromJSON(steps.data.outputs.pr).number }}
          ACTION_URL: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}

      - name: Comment on results
        if: always()
        uses: hasura/comment-progress@v2.1.0
        with:
          id: canary-publish-comment-${{ github.run_id }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.repository }}
          number: ${{ github.event.issue.number }}
          message: ${{ fromJSON(steps.comment.outputs.result).message }}
