name: canary remove

on:
  issue_comment:
    types: [ created ]

jobs:

  canary-remove:
    name: canary-remove
    runs-on: ubuntu-latest
    if:
      (github.event.comment.author_association == 'MEMBER' || github.event.comment.author_association == 'OWNER' || github.event.comment.author_association == 'CONTRIBUTOR') &&
      startsWith(github.event.comment.body, '/canary-remove')
    steps:
      - name: Comment to command
        uses: hasura/comment-progress@v2.1.0
        with:
          id: canary-remove-comment-${{ github.run_id }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.repository }}
          number: ${{ github.event.issue.number }}
          message: |
            > /canary-remove

            Trying to remove canary version...
            If you want to see detailed execution status, please [click here](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}).

      - name: checkout pull request version
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.issue.head.sha }}

      - name: get pr information
        uses: actions/github-script@v4
        id: pr
        with:
          script: |
            const { getPrData } = require('./.github/scripts');
            return await getPrData({ github, context, core });

      - name: setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 14.x

      - name: set npm autority
        run: |
          yarn logout
          echo "@apollo-elements:registry=http://registry.npmjs.org/" > .npmrc
          echo "registry=http://registry.npmjs.org/" >> .npmrc
          echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> .npmrc
          npm whoami
        env:
          NPM_TOKEN: ${{ secrets.npm_token }}

      - name: install dependencies
        run: |
          yarn install
          yarn add @actions/exec -W

      - name: get lerna packages list
        id: packages
        run: echo "::set-output name=list::$(lerna list --json | awk '{print}' ORS='')"

      - name: remove canary tag
        uses: actions/github-script@v4
        id: removed-packages
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const exec = require('@actions/exec');

            const { NUMBER } = process.env;

            let { LIST } = process.env;
            LIST = JSON.parse(LIST);

            const statusList = LIST.reduce((statusList, item) => {
              statusList[item.name] = true;
              return statusList;
            }, {});

            core.info('start unpublish canary version');
            const promises = LIST.map(async (item) => {
              core.startGroup(`${item.name}`);
              try {
                core.info(`Try to unpublish tag: ${item.name}@alpha-${NUMBER}`);
                await exec.exec(`npm dist-tag rm ${item.name} alpha-${NUMBER}`);
                core.info(`Unpublish tag success: ${item.name}@alpha-${NUMBER}`);
              } catch (error) {
                statusList[item.name] = false;
                core.warning(`Unpublish tag failed: ${item.name}@alpha-${NUMBER} `);
                return;
              }

              let versionList = [];
              try {
                core.info('Get version info from tag');
                const versionListJSON = await exec.exec(`npm view ${item.name} versions --json`);
                versionList = JSON.parse(versionListJSON);
              } catch (error) {
                core.warning(`Get version info failed: ${item.name}@alpha-${NUMBER}`);
                return;
              }

              const versionRegexp = /1.0.18-alpha-9.30/g;
              const canaryVersionList = versionList.filter((version) => versionRegexp.test(version));

              await Promise.all(
                canaryVersionList.forEach(async (version) => {
                  try {
                    core.info(`Try to remove canary version: ${item.name}@${version}`);
                    await exec.exec(`npm unpublish ${item.name}@${version}`);
                    core.info(`Remove canary version success: ${item.name}@${version}`);
                  } catch (error) {
                    core.warning(`Remove canary version failed: ${item.name}@${version}`);
                  }
                })
              );
            });

            await Promise.all(promises);
            core.info('finish unpublish canary version');

            let errorCount = 0;
            const removedPackages = [];
            for (const name in statusList) {
              if (!statusList[name]) errorCount++;
              else removedPackages.push(name);
            }

            core.info(`Packages count: ${LIST.length}\nError count: ${errorCount}`);

            if (errorCount >= LIST.length) {
              core.setFailed('Failed to delete tags from all packages.');
              return [];
            }

            return removedPackages;

        env:
          LIST: ${{ steps.packages.outputs.list }}
          NUMBER: ${{ fromJSON(steps.pr.outputs.result).number }}

      - name: make comment
        if: always()
        id: comment
        uses: actions/github-script@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { STATUS, TAG, ACTION_URL, REMOVED_PACKAGES } = process.env;

            let message = "> /canary-remove\r\n\r\n";

            switch (STATUS) {
              case 'success':
                message += `🎉 canary remove complete!\r\nRemoved tag is \`${TAG}\`\r\n\r\n`;
                message += '**List of packages with tags removed**\r\n'
                REMOVED_PACKAGES.forEach((package) => {
                  message += `- ${package}\r\n`
                });

                break;

              case 'failure':
                message += `❗ canary remove failed.\r\nCheck error in github [action page](${ACTION_URL}).\r\n`;
                break;
            }

            return { message };
        env:
          STATUS: ${{ job.status }}
          TAG: alpha-${{ fromJSON(steps.pr.outputs.result).number }}
          ACTION_URL: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}
          REMOVED_PACKAGES: ${{ steps.removed-packages.outputs.result }}

      - name: Comment on results
        if: always()
        uses: hasura/comment-progress@v2.1.0
        with:
          id: canary-remove-comment-${{ github.run_id }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.repository }}
          number: ${{ github.event.issue.number }}
          message: ${{ fromJSON(steps.comment.outputs.result).message }}
