name: canary remove

on:
  issue_comment:
    types: [ created ]

jobs:

  canary-remove:
    name: canary-remove
    runs-on: ubuntu-latest
    if:
      (github.event.comment.author_association == 'MEMBER' || github.event.comment.author_association == 'OWNER' || github.event.comment.author_association == 'CONTRIBUTOR') &&
      startsWith(github.event.comment.body, '/canary-remove')
    steps:
      - name: Comment to command
        uses: hasura/comment-progress@v2.1.0
        with:
          id: canary-remove-comment-${{ github.run_id }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.repository }}
          number: ${{ github.event.issue.number }}
          message: |
            > /canary-remove

            Trying to remove canary version...
            If you want to see detailed execution status, please [click here](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}).

      - name: checkout pull request version
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.issue.head.sha }}

      - name: get pr information
        uses: actions/github-script@v4
        id: pr
        with:
          script: |
            const { getPrData } = require('./.github/scripts');
            return await getPrData({ github, context, core });

      - name: setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 14.x

      - name: set npm autority
        run: |
          yarn logout
          echo "@apollo-elements:registry=http://registry.npmjs.org/" > .npmrc
          echo "registry=http://registry.npmjs.org/" >> .npmrc
          echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> .npmrc
          npm whoami
        env:
          NPM_TOKEN: ${{ secrets.npm_token }}

      - name: install dependencies
        run: |
          yarn install
          yarn add @actions/exec -W

      - name: get lerna packages list
        id: packages
        run: echo "::set-output name=list::$(lerna list --json | awk '{print}' ORS='')"

      - name: remove canary tag
        uses: actions/github-script@v4
        id: removed-packages
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const exec = require('@actions/exec');

            const { NUMBER } = process.env;

            let { LIST } = process.env;
            LIST = JSON.parse(LIST);

            const packageList = LIST.map((item) => item.name);

            const removedPackage = [];

            core.info('start unpublish canary version');

            for (const name of packageList) {
              core.startGroup(name);

              let removed = false;

              try {
                core.info(`Try to unpublish tag: ${name}@alpha-${NUMBER}`);
                await exec.exec(`npm dist-tag rm ${name} alpha-${NUMBER}`);

                core.info(`Unpublish tag success: ${name}@alpha-${NUMBER}`);
                removed = true;
              } catch (error) {
                core.warning(`Unpublish tag failed: ${name}@alpha-${NUMBER} `);
              }

              let versionList = [];
              try {
                core.info('Get version info from tag');

                const outputList = [];
                let error = false;

                await exec.exec(`npm view ${name} versions --json`, [], {
                  listeners: {
                    stdout: (data) => {
                      outputList.push(data.toString());
                    },
                    stderr: (data) => {
                      error = true;
                    }
                  }
                });

                if (error) throw new Error('get version failed');

                versionList = JSON.parse(outputList.join(''));
              } catch (error) {
                core.warning(`Get version info failed: ${name}@alpha-${NUMBER}`);
                return;
              }

              const versionRegexp = /1.0.18-alpha-9.30/g;
              const canaryVersionList = versionList.filter((version) => versionRegexp.test(version));

              core.info(`canary type : ${typeof canaryVersionList}, versionList type : ${typeof versionList}`);
              core.info(`canary version list : ${JSON.stringify(canaryVersionList)}`);

              const promise = canaryVersionList.forEach(async (version) => {
                try {
                  core.info(`Try to remove canary version: ${name}@${version}`);
                  await exec.exec(`npm unpublish ${name}@${version}`);
                  core.info(`Remove canary version success: ${name}@${version}`);
                  removed = true;
                } catch (error) {
                  core.warning(`Remove canary version failed: ${name}@${version}`);
                }
              });

              await Promise.all(promise);

              if (removed) removedPackage.push(name);

              core.endGroup();
            }

            core.info('finish unpublish canary version');

            return removedPackages;

        env:
          LIST: ${{ steps.packages.outputs.list }}
          NUMBER: ${{ fromJSON(steps.pr.outputs.result).number }}

      - name: make comment
        if: always()
        id: comment
        uses: actions/github-script@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { STATUS, TAG, ACTION_URL, REMOVED_PACKAGES } = process.env;

            let message = "> /canary-remove\r\n\r\n";

            switch (STATUS) {
              case 'success':
                message += `🎉 canary remove complete!\r\nRemoved tag is \`${TAG}\`\r\n\r\n`;
                message += '**List of packages with tags removed**\r\n'
                REMOVED_PACKAGES.forEach((package) => {
                  message += `- ${package}\r\n`
                });

                break;

              case 'failure':
                message += `❗ canary remove failed.\r\nCheck error in github [action page](${ACTION_URL}).\r\n`;
                break;
            }

            return { message };
        env:
          STATUS: ${{ job.status }}
          TAG: alpha-${{ fromJSON(steps.pr.outputs.result).number }}
          ACTION_URL: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}
          REMOVED_PACKAGES: ${{ steps.removed-packages.outputs.result }}

      - name: Comment on results
        if: always()
        uses: hasura/comment-progress@v2.1.0
        with:
          id: canary-remove-comment-${{ github.run_id }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.repository }}
          number: ${{ github.event.issue.number }}
          message: ${{ fromJSON(steps.comment.outputs.result).message }}
