name: check pull request branch

on:
  pull_request:
    branches: ["main"]
    types: [opened, synchronize, reopened, edited]

jobs:
  check-branch:
    name: check branch
    runs-on: ubuntu-latest
    steps:
      - name: check release branch
        if: ${{ github.event.pull_request.head.ref != 'release' }}
        run: echo "::error ::Not a release branch"