name: preprelease publish

on:
  pull_request:
    branches: [release]
    types: [closed]

jobs:
  publish-prerelease-version:
    name: publish prerelease version
    runs-on: ubuntu-latest
    if: ${{ !github.event.pull_request.merged }}
    steps:
      - name: checkout pull request version
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: get pr information
        uses: actions/github-script@v4
        id: pr
        with:
          script: |
            const getPrData = require('./.github/scripts/getPrData');
            return await getPrData({ github, context, core });

      - name: echo pr
        run: echo ${{ steps.pr.outputs.result }}



