name: publish release version

on:
  push:
    branches: 
      - main

jobs:
  CD:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2

      - name: config git user
        run: |
          git config user.name github-actions
          git config user.emil wtae1216@gmail.com

      - name: config npm token
        run: |
          yarn logout
          echo "@apollo-elements:registry=http://registry.npmjs.org/" > .npmrc
          echo "registry=http://registry.npmjs.org/" >> .npmrc
          echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> .npmrc
          npm whoami
        env:
          NPM_TOKEN: ${{ secrets.npm_token }}

      - name: install packages
        run: yarn install

      - name: create release version
        run: |
          lerna version -m "create release version" --yes

      - name: publish test version
        run: lerna publish from-package --yes
