name: check allow pull request

on:
  pull_request:
    branches: [ "main", "release" ]
    types: [opened, synchronize, reopened]

jobs:
  pull-request-ci:
    name: pull request ci
    runs-on: ubuntu-latest
    steps:
      - name: echo event
        env:
          GITHUB_CONTEXT: ${{ toJSON(github.event) }}
        run: echo "$GITHUB_CONTEXT"

      - name: Comment to pull request
        uses: hasura/comment-progress@v2.1.0
        with:
          id: canary-publish-comment-${{ github.run_id }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.repository }}
          number: ${{ github.event.issue.number }}
          message: |
            > pull request CI

            Executing CI for pull request verification.
            If you want to see detailed execution status, please [click here](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}).

      - name: checkout pull request version
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 14.x

      - name: install dependencies
        run: yarn install

      - name: Testing the packages
        run: lerna run test:silent

      - name: Check if packages are buildable
        run: lerna run build
