name: check allow pull request

on:
  pull_request:
    branches: [ "main", "release" ]
    types: [opened, edited, synchronize, reopened]

jobs:
  pull-request-ci:
    name: pull request ci
    runs-on: ubuntu-latest
    steps:
      - name: checkout master
        uses: actions/checkout@v2

      - name: check current branch
        run: |
          git branch --show-current
          echo "current branch : $(git branch --show-current)\r\nsha : ${{ github.event.pull_request.head.sha }}"